# Week-1 visualization companion for RStudio.
#
# Open this file in RStudio and click Source, or run:
# E:\R\R-4.5.2\bin\Rscript.exe notebooks\02_w1_visualization_rstudio.R
#
# The CSV inputs are generated by src/09_visualize_w1_python.py.  This keeps
# Python and RStudio figures on the same cleaned-data definitions.

# The machine-level R profile requests C.UTF-8, which Windows does not expose.
# Select the installed Windows UTF-8 locale before resolving the Chinese path.
invisible(try(Sys.setlocale("LC_ALL", "Chinese (Simplified)_China.utf8"), silent = TRUE))

suppressPackageStartupMessages({
  library(ggplot2)
  library(readr)
  library(scales)
  library(grid)
})

args_full <- commandArgs(trailingOnly = FALSE)
script_flag <- grep("^--file=", args_full, value = TRUE)
if (length(script_flag) > 0) {
  script_path <- normalizePath(sub("^--file=", "", script_flag[1]), winslash = "/")
  project_root <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/")
} else {
  project_root <- normalizePath(getwd(), winslash = "/")
}

input_dir <- file.path(project_root, "outputs", "tables", "w1_visualization")
output_dir <- file.path(project_root, "outputs", "figures", "w1_rstudio")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

blue <- "#2F6B9A"
blue_light <- "#BFD7EA"
gold <- "#D9A441"
orange <- "#D97706"
olive <- "#728C3B"
pink <- "#C65A78"
mid <- "#6B7280"
ink <- "#222222"
open <- "#EFF3F7"
grid_color <- "#D9DEE5"

batch_colors <- c("Batch 1" = blue, "Batch 2" = gold, "Batch 3" = orange)
model_colors <- c(
  "persistence" = mid,
  "seasonal_naive" = gold,
  "xgboost" = blue
)

theme_w1 <- theme_minimal(base_size = 11) +
  theme(
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(colour = grid_color, linewidth = 0.35),
    plot.title = element_text(face = "bold", colour = ink, size = 14),
    plot.subtitle = element_text(colour = mid, size = 9),
    plot.caption = element_text(colour = mid, size = 8, hjust = 0),
    axis.title = element_text(colour = ink),
    axis.text = element_text(colour = ink),
    legend.position = "bottom",
    legend.title = element_blank(),
    strip.text = element_text(face = "bold", colour = ink)
  )

save_w1 <- function(plot, filename, width = 11, height = 6.2) {
  path <- file.path(output_dir, filename)
  ggsave(path, plot = plot, width = width, height = height, dpi = 180, bg = "white")
  path
}

quality <- read_csv(file.path(input_dir, "w1_quality_summary.csv"), show_col_types = FALSE)
daily <- read_csv(file.path(input_dir, "w1_daily_requests.csv"), show_col_types = FALSE)
token_hist <- read_csv(file.path(input_dir, "w1_token_histogram.csv"), show_col_types = FALSE)
composition <- read_csv(file.path(input_dir, "w1_category_composition.csv"), show_col_types = FALSE)
field_support <- read_csv(file.path(input_dir, "w1_field_support.csv"), show_col_types = FALSE)
literature <- read_csv(file.path(input_dir, "w1_literature_theme_matrix.csv"), show_col_types = FALSE)
smoke <- read_csv(file.path(input_dir, "w1_smoke_2days.csv"), show_col_types = FALSE)
metrics <- read_csv(file.path(input_dir, "w1_preliminary_model_metrics.csv"), show_col_types = FALSE)

quality$batch <- factor(quality$batch, levels = c("Batch 1", "Batch 2", "Batch 3"))
daily$batch <- factor(daily$batch, levels = c("Batch 1", "Batch 2"))
token_hist$batch <- factor(token_hist$batch, levels = c("Batch 1", "Batch 2"))

# R-W1-01: cleaning retention.
retention <- rbind(
  data.frame(batch = quality$batch, stage = "Raw", requests = quality$raw_rows),
  data.frame(batch = quality$batch, stage = "Cleaned", requests = quality$clean_rows)
)
retention$stage <- factor(retention$stage, levels = c("Raw", "Cleaned"))
p1 <- ggplot(retention, aes(x = batch, y = requests / 1e6, fill = stage)) +
  geom_col(position = position_dodge(width = 0.78), width = 0.70) +
  geom_text(
    data = quality,
    aes(x = batch, y = clean_rows / 1e6, label = sprintf("-%.2f%%", deletion_pct)),
    inherit.aes = FALSE,
    vjust = -0.7,
    size = 3.2,
    colour = ink
  ) +
  scale_fill_manual(values = c("Raw" = blue_light, "Cleaned" = blue)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  labs(
    title = "R-W1-01 Cleaning retention by batch",
    subtitle = "Exact all-field duplicates were the only removed records",
    x = NULL,
    y = "Requests (millions)",
    caption = "Source: w1_quality_summary.csv"
  ) + theme_w1

# R-W1-02: field-support matrix.
field_levels <- unique(field_support$field)
field_support$field <- factor(field_support$field, levels = rev(field_levels))
field_support$batch <- factor(field_support$batch, levels = c("Batch 1", "Batch 2", "Batch 3"))
p2 <- ggplot(field_support, aes(x = batch, y = field, fill = status)) +
  geom_tile(colour = "white", linewidth = 0.7) +
  geom_text(aes(label = ifelse(support == 1, "Yes", ifelse(support == 0.5, "Partial", "No"))), size = 3) +
  scale_fill_manual(values = c(
    "Not provided" = "#E7E9ED",
    "Partial / audit only" = gold,
    "Provided" = blue
  )) +
  labs(
    title = "R-W1-02 Source-field availability",
    subtitle = "Session and elapsed-time fields do not support the main Batch 1/2 model",
    x = NULL,
    y = NULL,
    caption = "Source: sampled CSV schemas and data dictionary"
  ) + theme_w1 +
  theme(panel.grid = element_blank())

# R-W1-03: batch time coverage.
quality$start_day <- quality$timestamp_min_relative_seconds / 86400
quality$end_day <- quality$timestamp_max_relative_seconds / 86400
p3 <- ggplot(quality, aes(y = batch, colour = batch)) +
  geom_segment(
    aes(x = start_day, xend = end_day, yend = batch),
    linewidth = 8,
    lineend = "butt"
  ) +
  geom_text(
    aes(x = end_day + 4, label = sprintf("%.1f days", duration_days_inclusive)),
    colour = ink,
    hjust = 0,
    size = 3.2
  ) +
  scale_colour_manual(values = batch_colors) +
  scale_x_continuous(limits = c(0, max(quality$end_day) + 30), expand = c(0, 0)) +
  labs(
    title = "R-W1-03 Batch time coverage",
    subtitle = "Batch 3 starts after an approximately 104-day gap and remains robustness-only",
    x = "Relative day",
    y = NULL,
    caption = "Source: w1_quality_summary.csv; calendar origin is undisclosed"
  ) + theme_w1 +
  theme(legend.position = "none")

# R-W1-04: daily request volume.
p4 <- ggplot(daily, aes(x = relative_day, y = request_count / 1000, colour = batch)) +
  geom_line(linewidth = 0.9) +
  scale_colour_manual(values = batch_colors) +
  labs(
    title = "R-W1-04 Daily request volume",
    subtitle = "Cleaned Batch 1/2 requests; traffic level is strongly non-stationary",
    x = "Relative day",
    y = "Requests (thousands/day)",
    caption = "Source: w1_daily_requests.csv"
  ) + theme_w1

# R-W1-05: token-tail distribution.
token_hist$token_mid <- exp(token_hist$log_bin_mid) - 1
p5 <- ggplot(subset(token_hist, request_share > 0), aes(x = token_mid, y = request_share, colour = batch)) +
  geom_step(linewidth = 0.9) +
  scale_x_log10(labels = label_number(big.mark = ",")) +
  scale_y_log10(labels = label_scientific()) +
  scale_colour_manual(values = batch_colors) +
  labs(
    title = "R-W1-05 Request-level total-token distribution",
    subtitle = "Full cleaned Batch 1/2 distributions shown on log-log axes",
    x = "Total tokens per request (log scale)",
    y = "Share of requests per bin (log scale)",
    caption = "Source: w1_token_histogram.csv"
  ) + theme_w1

# R-W1-06: model and log-type composition.
category_colors <- c(
  "ChatGPT" = blue,
  "GPT-4" = gold,
  "API log" = olive,
  "Conversation log" = orange
)
composition$batch <- factor(composition$batch, levels = c("Batch 1", "Batch 2", "Batch 3"))
p6 <- ggplot(composition, aes(x = share, y = batch, fill = category)) +
  geom_col(width = 0.72) +
  facet_wrap(~dimension, ncol = 1) +
  scale_x_continuous(labels = label_percent(accuracy = 1), expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 1)) +
  scale_fill_manual(values = category_colors) +
  labs(
    title = "R-W1-06 Model and log-type composition",
    subtitle = "Raw audit composition across all three published batches",
    x = "Share of requests",
    y = NULL,
    caption = "Source: w1_category_composition.csv"
  ) + theme_w1

# R-W1-07: two-day smoke-test profile.
smoke_long <- rbind(
  data.frame(relative_hour = smoke$relative_hour, metric = "Total tokens / 5 min", value = smoke$total_tokens),
  data.frame(relative_hour = smoke$relative_hour, metric = "Requests / 5 min", value = smoke$request_count)
)
p7 <- ggplot(smoke_long, aes(x = relative_hour, y = value, colour = metric)) +
  geom_line(linewidth = 0.55) +
  facet_wrap(~metric, ncol = 1, scales = "free_y") +
  scale_colour_manual(values = c("Total tokens / 5 min" = blue, "Requests / 5 min" = gold)) +
  labs(
    title = "R-W1-07 Two-day end-to-end smoke-test profile",
    subtitle = sprintf(
      "576 bins | %s requests | %s tokens",
      comma(sum(smoke$request_count)),
      comma(sum(smoke$total_tokens))
    ),
    x = "Hours from smoke-test start",
    y = NULL,
    caption = "Source: w1_smoke_2days.csv"
  ) + theme_w1 +
  theme(legend.position = "none")

# R-W1-08: literature evidence themes.
literature$paper <- factor(literature$paper, levels = rev(unique(literature$paper)))
literature$theme <- factor(literature$theme, levels = unique(literature$theme))
p8 <- ggplot(literature, aes(x = theme, y = paper, fill = factor(covered))) +
  geom_tile(colour = "white", linewidth = 0.5) +
  geom_point(data = subset(literature, covered == 1), colour = "white", size = 1.6) +
  scale_fill_manual(values = c("0" = open, "1" = blue)) +
  labs(
    title = "R-W1-08 Literature evidence themes",
    subtitle = "Twelve priority papers; marks denote thematic coverage rather than quality",
    x = NULL,
    y = NULL,
    caption = "Source: w1_literature_theme_matrix.csv"
  ) + theme_w1 +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1)
  )

# R-W1-09: preliminary model results.
metrics$split <- factor(metrics$split, levels = c("validation", "test"))
metrics$model <- factor(metrics$model, levels = c("persistence", "seasonal_naive", "xgboost"))
metric_long <- rbind(
  data.frame(split = metrics$split, model = metrics$model, metric = "MAE (tokens / 5 min)", value = metrics$mae),
  data.frame(split = metrics$split, model = metrics$model, metric = "Burst F1 at fixed P95", value = metrics$f1)
)
metric_long$metric <- factor(
  metric_long$metric,
  levels = c("MAE (tokens / 5 min)", "Burst F1 at fixed P95")
)
metric_long$label <- ifelse(
  metric_long$metric == "MAE (tokens / 5 min)",
  sprintf("%.1fk", metric_long$value / 1000),
  sprintf("%.3f", metric_long$value)
)
p9 <- ggplot(metric_long, aes(x = split, y = value, fill = model)) +
  geom_col(position = position_dodge(width = 0.78), width = 0.72) +
  geom_text(
    aes(label = label),
    position = position_dodge(width = 0.78),
    vjust = -0.35,
    size = 3
  ) +
  facet_wrap(~metric, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  scale_fill_manual(values = model_colors) +
  labs(
    title = "R-W1-09 Preliminary 15-minute-ahead model results",
    subtitle = "Cleaned Parquet and chronological 70/15/15 split; LSTM was unavailable in W1",
    x = NULL,
    y = NULL,
    caption = "Source: w1_preliminary_model_metrics.csv"
  ) + theme_w1

plots <- list(p1, p2, p3, p4, p5, p6, p7, p8, p9)
filenames <- c(
  "fig_w1_r_01_cleaning_retention.png",
  "fig_w1_r_02_field_support.png",
  "fig_w1_r_03_batch_time_coverage.png",
  "fig_w1_r_04_daily_requests.png",
  "fig_w1_r_05_token_distribution.png",
  "fig_w1_r_06_category_composition.png",
  "fig_w1_r_07_smoke_profile.png",
  "fig_w1_r_08_literature_themes.png",
  "fig_w1_r_09_preliminary_models.png"
)

for (index in seq_along(plots)) {
  save_w1(plots[[index]], filenames[index])
}

# A compact 3x3 contact sheet for review in RStudio or the file explorer.
overview_path <- file.path(output_dir, "w1_rstudio_overview.png")
png(overview_path, width = 3000, height = 2400, res = 160, bg = "white")
grid.newpage()
pushViewport(viewport(layout = grid.layout(3, 3)))
for (index in seq_along(plots)) {
  row <- ((index - 1) %/% 3) + 1
  column <- ((index - 1) %% 3) + 1
  compact <- plots[[index]] + theme_w1 +
    theme(
      plot.title = element_text(size = 8),
      plot.subtitle = element_text(size = 5.5),
      plot.caption = element_blank(),
      axis.title = element_text(size = 6),
      axis.text = element_text(size = 5),
      legend.text = element_text(size = 5),
      strip.text = element_text(size = 5.5)
    )
  print(compact, vp = viewport(layout.pos.row = row, layout.pos.col = column))
}
dev.off()

capture.output(sessionInfo(), file = file.path(input_dir, "r_session_info.txt"))
cat(sprintf("Created %d RStudio figures and overview: %s\n", length(plots), overview_path))
